"""
Comprehensive Paint Color Database - ALL major colors from each brand
"""
import asyncio
import os
from datetime import datetime, timezone
import uuid
from motor.motor_asyncio import AsyncIOMotorClient

mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ.get('DB_NAME', 'interior_design_db')]

# ============================================
# BENJAMIN MOORE - COMPREHENSIVE COLOR PALETTE
# ============================================
BENJAMIN_MOORE_COLORS = [
    # WHITES
    {"name": "White Dove", "code": "OC-17", "hex": "#F3EEE4"},
    {"name": "Simply White", "code": "OC-117", "hex": "#F8F6F0"},
    {"name": "Chantilly Lace", "code": "OC-65", "hex": "#F5F3EF"},
    {"name": "Decorator's White", "code": "OC-149", "hex": "#ECEAE3"},
    {"name": "Cloud White", "code": "OC-130", "hex": "#F2EEE4"},
    {"name": "Swiss Coffee", "code": "OC-45", "hex": "#F0EBDD"},
    {"name": "White Heron", "code": "OC-57", "hex": "#F4F1E8"},
    {"name": "Atrium White", "code": "OC-145", "hex": "#F0EDE4"},
    {"name": "Linen White", "code": "OC-146", "hex": "#EDE8DC"},
    {"name": "Acadia White", "code": "OC-38", "hex": "#F1EDE3"},
    {"name": "Paper White", "code": "OC-55", "hex": "#EFEBE2"},
    {"name": "Mountain Peak White", "code": "OC-121", "hex": "#F3F0E8"},
    {"name": "Ivory White", "code": "OC-115", "hex": "#F2EEE1"},
    {"name": "Seashell", "code": "OC-120", "hex": "#F5F0E5"},
    {"name": "Snowfall White", "code": "OC-118", "hex": "#F6F3EC"},
    {"name": "Cotton Balls", "code": "OC-122", "hex": "#F5F2EB"},
    {"name": "Wedding Veil", "code": "OC-101", "hex": "#F4F1EA"},
    {"name": "Winter White", "code": "OC-21", "hex": "#F3EFE5"},
    {"name": "Steam", "code": "OC-128", "hex": "#F0EBE0"},
    {"name": "Antique White", "code": "OC-83", "hex": "#F0E8D8"},
    # GRAYS
    {"name": "Revere Pewter", "code": "HC-172", "hex": "#C4BAA2"},
    {"name": "Edgecomb Gray", "code": "HC-173", "hex": "#D3CABC"},
    {"name": "Pale Oak", "code": "OC-20", "hex": "#DDD5C9"},
    {"name": "Balboa Mist", "code": "OC-27", "hex": "#D7D2C4"},
    {"name": "Classic Gray", "code": "OC-23", "hex": "#D5D0C8"},
    {"name": "Gray Owl", "code": "OC-52", "hex": "#C5C2B9"},
    {"name": "Stonington Gray", "code": "HC-170", "hex": "#B9B7AC"},
    {"name": "Wickham Gray", "code": "HC-171", "hex": "#C7C4BA"},
    {"name": "Chelsea Gray", "code": "HC-168", "hex": "#8C8984"},
    {"name": "Kendall Charcoal", "code": "HC-166", "hex": "#686763"},
    {"name": "Coventry Gray", "code": "HC-169", "hex": "#A8A69E"},
    {"name": "Metropolis", "code": "CC-546", "hex": "#7D7B73"},
    {"name": "Graphite", "code": "1603", "hex": "#5E5D59"},
    {"name": "Galveston Gray", "code": "HC-159", "hex": "#9B9890"},
    {"name": "Harbor Gray", "code": "AC-25", "hex": "#9FA19D"},
    {"name": "Silver Chain", "code": "1472", "hex": "#C0BDB6"},
    {"name": "Nimbus", "code": "1465", "hex": "#DCDAD6"},
    {"name": "Smoke", "code": "2122-40", "hex": "#C2C6C9"},
    {"name": "Thundercloud Gray", "code": "2124-40", "hex": "#A8ACB0"},
    {"name": "Pigeon Gray", "code": "2133-50", "hex": "#BABDBA"},
    {"name": "Fieldstone", "code": "1558", "hex": "#8A8781"},
    {"name": "Amherst Gray", "code": "HC-167", "hex": "#6B6B65"},
    {"name": "Iron Mountain", "code": "2134-30", "hex": "#5A5C5A"},
    {"name": "Graystone", "code": "1475", "hex": "#A09D96"},
    {"name": "Thunder", "code": "AF-685", "hex": "#747370"},
    {"name": "Sparrow", "code": "AF-720", "hex": "#6E6C66"},
    {"name": "Gray Cashmere", "code": "2138-60", "hex": "#C5C9C5"},
    {"name": "Horizon Gray", "code": "2141-50", "hex": "#B4B8B9"},
    {"name": "Silver Fox", "code": "2108-50", "hex": "#C4C4C0"},
    # BLUES
    {"name": "Hale Navy", "code": "HC-154", "hex": "#3E4B59"},
    {"name": "Newburyport Blue", "code": "HC-155", "hex": "#4E5B67"},
    {"name": "Van Deusen Blue", "code": "HC-156", "hex": "#486983"},
    {"name": "Gentleman's Gray", "code": "2062-20", "hex": "#3B4557"},
    {"name": "Sea Salt", "code": "2040-50", "hex": "#D1D8D8"},
    {"name": "Palladian Blue", "code": "HC-144", "hex": "#B5C5C1"},
    {"name": "Wythe Blue", "code": "HC-143", "hex": "#A8BEB3"},
    {"name": "Aegean Teal", "code": "2136-40", "hex": "#79A6A5"},
    {"name": "Summer Shower", "code": "2135-60", "hex": "#C8D5D5"},
    {"name": "Beach Glass", "code": "1564", "hex": "#B4C4BC"},
    {"name": "Woodlawn Blue", "code": "HC-147", "hex": "#9CB4B1"},
    {"name": "Wedgewood Gray", "code": "HC-146", "hex": "#9AACA9"},
    {"name": "Mount Saint Anne", "code": "1565", "hex": "#8BA8A6"},
    {"name": "Jamestown Blue", "code": "HC-148", "hex": "#7A9B99"},
    {"name": "Province Blue", "code": "2135-40", "hex": "#718D8D"},
    {"name": "Narragansett Green", "code": "HC-157", "hex": "#5B7A73"},
    {"name": "Knoxville Gray", "code": "HC-160", "hex": "#7D9390"},
    {"name": "Blue Note", "code": "2129-30", "hex": "#50606A"},
    {"name": "Normandy", "code": "2129-40", "hex": "#6A7A85"},
    {"name": "Oxford Gray", "code": "2128-40", "hex": "#6B7F8A"},
    {"name": "Santorini Blue", "code": "1634", "hex": "#8FADB9"},
    {"name": "Nantucket Fog", "code": "AC-22", "hex": "#BCCBCB"},
    {"name": "Buxton Blue", "code": "HC-149", "hex": "#8CA3A6"},
    {"name": "Boothbay Gray", "code": "HC-165", "hex": "#A5B5B6"},
    {"name": "Gossamer Blue", "code": "2123-40", "hex": "#9BB3BB"},
    {"name": "Yarmouth Blue", "code": "HC-150", "hex": "#94ACB2"},
    {"name": "Colorado Gray", "code": "2136-50", "hex": "#A1BAB8"},
    {"name": "Breath of Fresh Air", "code": "806", "hex": "#C7D9E0"},
    {"name": "Ocean Air", "code": "2123-50", "hex": "#B8CBCF"},
    {"name": "Quiet Moments", "code": "1563", "hex": "#C3D4D4"},
    {"name": "Tranquility", "code": "AF-490", "hex": "#C6D8DA"},
    {"name": "Mountain Air", "code": "1640", "hex": "#D0DDDC"},
    {"name": "Arctic Blue", "code": "2050-60", "hex": "#C5D8E0"},
    {"name": "Blue Lace", "code": "1625", "hex": "#D6E3E6"},
    {"name": "Iceberg", "code": "2122-50", "hex": "#D4DFE2"},
    # GREENS
    {"name": "Saybrook Sage", "code": "HC-114", "hex": "#B0AF97"},
    {"name": "Soft Fern", "code": "2144-40", "hex": "#A8B59B"},
    {"name": "Fernwood Green", "code": "2145-40", "hex": "#8FA385"},
    {"name": "Cushing Green", "code": "HC-125", "hex": "#9AAB91"},
    {"name": "Louisburg Green", "code": "HC-113", "hex": "#A3A98F"},
    {"name": "Aganthus Green", "code": "HC-126", "hex": "#8A9B85"},
    {"name": "Guilford Green", "code": "HC-116", "hex": "#A5B09B"},
    {"name": "Hunter Green", "code": "2041-10", "hex": "#2E4D3A"},
    {"name": "Backwoods", "code": "469", "hex": "#4A5E46"},
    {"name": "Evergreen", "code": "2046-10", "hex": "#2D4A41"},
    {"name": "Tarrytown Green", "code": "HC-134", "hex": "#4D5E4F"},
    {"name": "Dakota Shadow", "code": "448", "hex": "#5A6B55"},
    {"name": "Sage", "code": "2143-30", "hex": "#7A856B"},
    {"name": "Rosemary", "code": "2148-30", "hex": "#5D6B50"},
    {"name": "Cedar Grove", "code": "444", "hex": "#6A7B61"},
    {"name": "Peale Green", "code": "HC-121", "hex": "#B5BAA0"},
    {"name": "Hancock Green", "code": "HC-117", "hex": "#97A084"},
    {"name": "Kennebunkport Green", "code": "HC-123", "hex": "#6E7C66"},
    {"name": "Mohegan Sage", "code": "2138-30", "hex": "#7D8872"},
    {"name": "Springfield Sage", "code": "HC-122", "hex": "#8E9A7F"},
    # NEUTRALS/BEIGES/TANS
    {"name": "Manchester Tan", "code": "HC-81", "hex": "#C3B193"},
    {"name": "Shaker Beige", "code": "HC-45", "hex": "#C6B89C"},
    {"name": "Lenox Tan", "code": "HC-44", "hex": "#C9B898"},
    {"name": "Bleeker Beige", "code": "HC-80", "hex": "#C4B69F"},
    {"name": "Bennington Gray", "code": "HC-82", "hex": "#B5A78F"},
    {"name": "Brandon Beige", "code": "OC-79", "hex": "#D4C9B5"},
    {"name": "Grant Beige", "code": "HC-83", "hex": "#BFB196"},
    {"name": "Philadelphia Cream", "code": "HC-30", "hex": "#D9CDB0"},
    {"name": "Weimaraner", "code": "AF-155", "hex": "#9E9080"},
    {"name": "Ashley Gray", "code": "HC-87", "hex": "#ABA18F"},
    {"name": "Tyler Taupe", "code": "HC-43", "hex": "#B9A98F"},
    {"name": "Powell Buff", "code": "HC-35", "hex": "#D3C4A7"},
    {"name": "Huntington Beige", "code": "HC-21", "hex": "#D7CABA"},
    {"name": "Monroe Bisque", "code": "HC-26", "hex": "#D9CEB7"},
    {"name": "Brandy Cream", "code": "OC-4", "hex": "#E7DCC5"},
    {"name": "Natural Linen", "code": "OC-107", "hex": "#DCCFBB"},
    {"name": "Muslin", "code": "OC-12", "hex": "#E2D9C8"},
    {"name": "Frappe", "code": "AF-85", "hex": "#D1C4B0"},
    {"name": "Alexandria Beige", "code": "HC-77", "hex": "#CBBFA5"},
    {"name": "Camelback", "code": "AC-34", "hex": "#CDBFA2"},
    # BLACKS & DARK COLORS
    {"name": "Black Panther", "code": "2125-10", "hex": "#393D3F"},
    {"name": "Onyx", "code": "2133-10", "hex": "#383838"},
    {"name": "Tricorn Black", "code": "2131-10", "hex": "#343434"},
    {"name": "Black", "code": "2132-10", "hex": "#2E2E2E"},
    {"name": "Jet Black", "code": "2120-10", "hex": "#2C2C2C"},
    {"name": "Soot", "code": "2129-20", "hex": "#3A3E41"},
    {"name": "Wrought Iron", "code": "2124-10", "hex": "#464646"},
    {"name": "Mopboard Black", "code": "CW-680", "hex": "#404040"},
    {"name": "Midnight Oil", "code": "1631", "hex": "#2C3539"},
    {"name": "Carbon Copy", "code": "2117-10", "hex": "#4A4A48"},
    # REDS/PINKS/CORALS
    {"name": "Caliente", "code": "AF-290", "hex": "#A43D3D"},
    {"name": "Heritage Red", "code": "HC-66", "hex": "#94403E"},
    {"name": "Pomegranate", "code": "AF-295", "hex": "#9C3D42"},
    {"name": "Raspberry Truffle", "code": "2080-10", "hex": "#8E3840"},
    {"name": "Dinner Party", "code": "AF-300", "hex": "#B53D46"},
    {"name": "Million Dollar Red", "code": "2003-10", "hex": "#C1272D"},
    {"name": "Exotic Red", "code": "2086-10", "hex": "#B42C31"},
    {"name": "Tucson Red", "code": "1300", "hex": "#A34044"},
    {"name": "Moroccan Red", "code": "1309", "hex": "#A03D3D"},
    {"name": "Pink Damask", "code": "OC-72", "hex": "#E9D8D1"},
    {"name": "Salmon Berry", "code": "2089-30", "hex": "#E5A69A"},
    {"name": "Coral Gables", "code": "2010-40", "hex": "#E4A396"},
    {"name": "Peach Parfait", "code": "2175-70", "hex": "#F2D5C9"},
    {"name": "Light Peach", "code": "2167-60", "hex": "#F5D5C3"},
    {"name": "Teacup Rose", "code": "2170-50", "hex": "#ECC0B3"},
    # YELLOWS/GOLDS
    {"name": "Hawthorne Yellow", "code": "HC-4", "hex": "#D9C98A"},
    {"name": "Barley", "code": "199", "hex": "#D6C899"},
    {"name": "Windham Cream", "code": "HC-6", "hex": "#DED0A4"},
    {"name": "Henderson Buff", "code": "HC-15", "hex": "#D9C99B"},
    {"name": "Crowne Hill Yellow", "code": "HC-10", "hex": "#D5C58D"},
    {"name": "Golden Straw", "code": "2152-50", "hex": "#E6D5A1"},
    {"name": "Stuart Gold", "code": "HC-10", "hex": "#D1B97D"},
    {"name": "Marblehead Gold", "code": "HC-11", "hex": "#CDB57B"},
    {"name": "Concord Ivory", "code": "HC-12", "hex": "#E2D4AD"},
    {"name": "Decatur Buff", "code": "HC-38", "hex": "#D7C8A2"},
    {"name": "Timothy Straw", "code": "2149-40", "hex": "#D6C88F"},
    {"name": "Yellow Highlighter", "code": "2021-30", "hex": "#F5E04D"},
    {"name": "Lemon Meringue", "code": "2023-50", "hex": "#F5E8A8"},
    {"name": "Goldfinch", "code": "HC-18", "hex": "#D4B563"},
    {"name": "Yellow Rain Coat", "code": "2020-40", "hex": "#F2D862"},
]

# ============================================
# SHERWIN WILLIAMS - COMPREHENSIVE PALETTE
# ============================================
SHERWIN_WILLIAMS_COLORS = [
    # WHITES
    {"name": "Alabaster", "code": "SW 7008", "hex": "#F2EDE3"},
    {"name": "Pure White", "code": "SW 7005", "hex": "#F1EDE6"},
    {"name": "Extra White", "code": "SW 7006", "hex": "#F1F0EA"},
    {"name": "Snowbound", "code": "SW 7004", "hex": "#EFEEE9"},
    {"name": "Greek Villa", "code": "SW 7551", "hex": "#F3EDE2"},
    {"name": "Creamy", "code": "SW 7012", "hex": "#EDE5D4"},
    {"name": "Dover White", "code": "SW 6385", "hex": "#F0EAE1"},
    {"name": "Pearly White", "code": "SW 7009", "hex": "#EBE6DB"},
    {"name": "Shoji White", "code": "SW 7042", "hex": "#EDE6D9"},
    {"name": "White Flour", "code": "SW 7102", "hex": "#EDE9E0"},
    {"name": "Westhighland White", "code": "SW 7566", "hex": "#F3EDE4"},
    {"name": "Marshmallow", "code": "SW 7001", "hex": "#F3EFE8"},
    {"name": "Ceiling Bright White", "code": "SW 7007", "hex": "#F4F3EF"},
    {"name": "High Reflective White", "code": "SW 7757", "hex": "#F7F6F2"},
    {"name": "Ivory Lace", "code": "SW 7013", "hex": "#EDE4D4"},
    {"name": "Navajo White", "code": "SW 6126", "hex": "#F2E5D1"},
    {"name": "Antique White", "code": "SW 6119", "hex": "#F5EAD9"},
    {"name": "Casa Blanca", "code": "SW 7571", "hex": "#F5EEDF"},
    {"name": "Moderate White", "code": "SW 6140", "hex": "#ECE4D4"},
    {"name": "Shell White", "code": "SW 8917", "hex": "#F0E7DA"},
    # GRAYS
    {"name": "Repose Gray", "code": "SW 7015", "hex": "#C2BDB3"},
    {"name": "Agreeable Gray", "code": "SW 7029", "hex": "#CEC8BC"},
    {"name": "Accessible Beige", "code": "SW 7036", "hex": "#CFC5B5"},
    {"name": "Mindful Gray", "code": "SW 7016", "hex": "#B4AFA5"},
    {"name": "Amazing Gray", "code": "SW 7044", "hex": "#A9A198"},
    {"name": "Dorian Gray", "code": "SW 7017", "hex": "#A19D94"},
    {"name": "Colonnade Gray", "code": "SW 7641", "hex": "#BDB6A9"},
    {"name": "Worldly Gray", "code": "SW 7043", "hex": "#BDB7AC"},
    {"name": "Passive", "code": "SW 7064", "hex": "#C8C5C0"},
    {"name": "Anew Gray", "code": "SW 7030", "hex": "#BCB5A9"},
    {"name": "Mega Greige", "code": "SW 7031", "hex": "#B3AB9E"},
    {"name": "Perfect Greige", "code": "SW 6073", "hex": "#BAB1A3"},
    {"name": "Requisite Gray", "code": "SW 7023", "hex": "#A89F94"},
    {"name": "Functional Gray", "code": "SW 7024", "hex": "#9E958A"},
    {"name": "Anonymous", "code": "SW 7046", "hex": "#9C9791"},
    {"name": "Gray Matters", "code": "SW 7066", "hex": "#9B9892"},
    {"name": "Modern Gray", "code": "SW 7632", "hex": "#A8A49D"},
    {"name": "Analytical Gray", "code": "SW 7051", "hex": "#AEA8A0"},
    {"name": "Ellie Gray", "code": "SW 7650", "hex": "#C5C0B9"},
    {"name": "Alpaca", "code": "SW 7022", "hex": "#B7AFA3"},
    {"name": "Intellectual Gray", "code": "SW 7045", "hex": "#8E8A84"},
    {"name": "Gauntlet Gray", "code": "SW 7019", "hex": "#827C74"},
    {"name": "Porpoise", "code": "SW 7047", "hex": "#75716A"},
    {"name": "Gibraltar", "code": "SW 6257", "hex": "#514E49"},
    {"name": "Peppercorn", "code": "SW 7674", "hex": "#5D5B5A"},
    {"name": "Iron Ore", "code": "SW 7069", "hex": "#4E4C4A"},
    {"name": "Black Fox", "code": "SW 7020", "hex": "#4D4843"},
    {"name": "Urbane Bronze", "code": "SW 7048", "hex": "#544D43"},
    {"name": "Tricorn Black", "code": "SW 6258", "hex": "#2E2E2E"},
    {"name": "Caviar", "code": "SW 6990", "hex": "#3A3A3C"},
    {"name": "Black Magic", "code": "SW 6991", "hex": "#3B3A39"},
    {"name": "Inkwell", "code": "SW 6992", "hex": "#3B3E44"},
    {"name": "Cyberspace", "code": "SW 7076", "hex": "#4E5358"},
    # BLUES
    {"name": "Sea Salt", "code": "SW 6204", "hex": "#C8D3CD"},
    {"name": "Comfort Gray", "code": "SW 6205", "hex": "#B5C4BB"},
    {"name": "Rainwashed", "code": "SW 6211", "hex": "#BFD1C8"},
    {"name": "Silvermist", "code": "SW 7621", "hex": "#C1CDCA"},
    {"name": "Naval", "code": "SW 6244", "hex": "#323B4C"},
    {"name": "In The Navy", "code": "SW 9178", "hex": "#2D3B4D"},
    {"name": "Anchors Aweigh", "code": "SW 9179", "hex": "#3E4756"},
    {"name": "Indigo Batik", "code": "SW 7602", "hex": "#3B4A5A"},
    {"name": "Gale Force", "code": "SW 7605", "hex": "#465766"},
    {"name": "Smoky Blue", "code": "SW 7604", "hex": "#546573"},
    {"name": "Nimbus Gray", "code": "SW 9170", "hex": "#C0C8CB"},
    {"name": "Krypton", "code": "SW 6247", "hex": "#9AADAB"},
    {"name": "Watery", "code": "SW 6478", "hex": "#B6CEC9"},
    {"name": "Tidewater", "code": "SW 6477", "hex": "#A9C4BF"},
    {"name": "Hazel", "code": "SW 6471", "hex": "#8EB4AD"},
    {"name": "Festoon Aqua", "code": "SW 0019", "hex": "#B4CCC8"},
    {"name": "Tradewind", "code": "SW 6218", "hex": "#9FBABA"},
    {"name": "Interesting Aqua", "code": "SW 6220", "hex": "#85A9A5"},
    {"name": "Riverway", "code": "SW 6222", "hex": "#6B8E8A"},
    {"name": "Still Water", "code": "SW 6223", "hex": "#4D706C"},
    {"name": "Refuge", "code": "SW 6228", "hex": "#3F5E5B"},
    {"name": "Rocky River", "code": "SW 6215", "hex": "#728E8B"},
    {"name": "Moody Blue", "code": "SW 6221", "hex": "#5C7D79"},
    {"name": "Waterscape", "code": "SW 6470", "hex": "#9AC0B9"},
    {"name": "Cay", "code": "SW 6772", "hex": "#62A99B"},
    {"name": "Breaktime", "code": "SW 6463", "hex": "#9DBAB4"},
    {"name": "Quietude", "code": "SW 6212", "hex": "#AAC5BD"},
    {"name": "Topsail", "code": "SW 6217", "hex": "#B5CECC"},
    {"name": "Rainwashed", "code": "SW 6211", "hex": "#BFD1C8"},
    {"name": "Waterfall", "code": "SW 6750", "hex": "#A2C4BF"},
    # GREENS
    {"name": "Evergreen Fog", "code": "SW 9130", "hex": "#8E9A8B"},
    {"name": "Retreat", "code": "SW 6207", "hex": "#7A8B7A"},
    {"name": "Privilege Green", "code": "SW 6193", "hex": "#8DA088"},
    {"name": "Dried Thyme", "code": "SW 6186", "hex": "#93A08A"},
    {"name": "Cascade Green", "code": "SW 0066", "hex": "#9EB4A1"},
    {"name": "Clary Sage", "code": "SW 6178", "hex": "#A5B099"},
    {"name": "Softened Green", "code": "SW 6177", "hex": "#B8C3AC"},
    {"name": "Contented", "code": "SW 6191", "hex": "#A8B79C"},
    {"name": "Nurture Green", "code": "SW 6451", "hex": "#B8C7A9"},
    {"name": "Recycled Glass", "code": "SW 7747", "hex": "#B8C8B3"},
    {"name": "Liveable Green", "code": "SW 6176", "hex": "#C3CCBA"},
    {"name": "Cucumber", "code": "SW 6722", "hex": "#B5CBA7"},
    {"name": "Ryegrass", "code": "SW 6423", "hex": "#C9D4A5"},
    {"name": "Bonsai Tint", "code": "SW 6436", "hex": "#CFD8B8"},
    {"name": "Honeydew", "code": "SW 6428", "hex": "#D8E5C0"},
    {"name": "Lacewing", "code": "SW 6729", "hex": "#DCEAC7"},
    {"name": "Topiary Tint", "code": "SW 6449", "hex": "#D4DFC2"},
    {"name": "Acacia Haze", "code": "SW 9132", "hex": "#A4AC95"},
    {"name": "Garden Sage", "code": "SW 7736", "hex": "#A6A990"},
    {"name": "Rosemary", "code": "SW 6187", "hex": "#868F76"},
    {"name": "Basil", "code": "SW 6194", "hex": "#6A7A5E"},
    {"name": "Cilantro", "code": "SW 0088", "hex": "#808E6F"},
    {"name": "Artichoke", "code": "SW 6179", "hex": "#9EA57E"},
    {"name": "Connected Gray", "code": "SW 6165", "hex": "#AAA791"},
    {"name": "Sage Green Light", "code": "SW 2851", "hex": "#B9BCA4"},
    {"name": "Svelte Sage", "code": "SW 6164", "hex": "#C5C4AD"},
    {"name": "Sage", "code": "SW 2860", "hex": "#9FA085"},
    {"name": "Forestwood", "code": "SW 7737", "hex": "#85896D"},
    {"name": "Espalier", "code": "SW 6734", "hex": "#8A9A68"},
    {"name": "Dill", "code": "SW 6438", "hex": "#ACC592"},
    # NEUTRALS/BEIGES
    {"name": "Natural Choice", "code": "SW 7011", "hex": "#E4DDD0"},
    {"name": "Kilim Beige", "code": "SW 6106", "hex": "#C8B8A3"},
    {"name": "Latte", "code": "SW 6108", "hex": "#C0AC95"},
    {"name": "Macadamia", "code": "SW 6142", "hex": "#D3C5AF"},
    {"name": "Antler Velvet", "code": "SW 9111", "hex": "#C4B199"},
    {"name": "Nomadic Desert", "code": "SW 6107", "hex": "#D1BDA6"},
    {"name": "Accessible Beige", "code": "SW 7036", "hex": "#CFC5B5"},
    {"name": "Balanced Beige", "code": "SW 7037", "hex": "#C4B7A6"},
    {"name": "Tony Taupe", "code": "SW 7038", "hex": "#A99E8C"},
    {"name": "Virtual Taupe", "code": "SW 7039", "hex": "#9B8F7E"},
    {"name": "Warm Stone", "code": "SW 7032", "hex": "#B3A595"},
    {"name": "Sanderling", "code": "SW 7513", "hex": "#CFBFAB"},
    {"name": "Pavilion Beige", "code": "SW 7512", "hex": "#C8B8A4"},
    {"name": "Jute Brown", "code": "SW 6096", "hex": "#B39E85"},
    {"name": "Sawdust", "code": "SW 6158", "hex": "#D5C6B2"},
    {"name": "Universal Khaki", "code": "SW 6150", "hex": "#B8A88A"},
    {"name": "Camelback", "code": "SW 6122", "hex": "#C7A982"},
    {"name": "Basket Beige", "code": "SW 6143", "hex": "#CCC0AB"},
    {"name": "Netsuke", "code": "SW 6133", "hex": "#D2C0A5"},
    {"name": "Believable Buff", "code": "SW 6120", "hex": "#DACEBC"},
    {"name": "Patience", "code": "SW 7555", "hex": "#DDC7A6"},
    {"name": "Blonde", "code": "SW 6128", "hex": "#DFCBA7"},
    {"name": "Ecru", "code": "SW 6135", "hex": "#DAD1BF"},
    {"name": "Muslin", "code": "SW 6133", "hex": "#DDD0BC"},
    # BLACKS
    {"name": "Tricorn Black", "code": "SW 6258", "hex": "#2E2E2E"},
    {"name": "Caviar", "code": "SW 6990", "hex": "#3A3A3C"},
    {"name": "Black Magic", "code": "SW 6991", "hex": "#3B3A39"},
    {"name": "Inkwell", "code": "SW 6992", "hex": "#3B3E44"},
    {"name": "Black Fox", "code": "SW 7020", "hex": "#4D4843"},
    {"name": "Iron Ore", "code": "SW 7069", "hex": "#4E4C4A"},
    {"name": "Peppercorn", "code": "SW 7674", "hex": "#5D5B5A"},
    {"name": "Urbane Bronze", "code": "SW 7048", "hex": "#544D43"},
    # YELLOWS
    {"name": "Ivoire", "code": "SW 6127", "hex": "#F2E7D1"},
    {"name": "Cornsilk", "code": "SW 6134", "hex": "#EEE4CC"},
    {"name": "Jersey Cream", "code": "SW 6379", "hex": "#F5E8CD"},
    {"name": "Banana Cream", "code": "SW 6673", "hex": "#F5E6B9"},
    {"name": "Butter Up", "code": "SW 6681", "hex": "#F5DDA0"},
    {"name": "Friendly Yellow", "code": "SW 6680", "hex": "#F2D68D"},
    {"name": "Overjoy", "code": "SW 6689", "hex": "#F1C862"},
    {"name": "Cheerful", "code": "SW 6903", "hex": "#F5D55E"},
    {"name": "Daisy", "code": "SW 6910", "hex": "#F7DC55"},
    {"name": "Lemon Twist", "code": "SW 6909", "hex": "#F5E058"},
    {"name": "Decisive Yellow", "code": "SW 6902", "hex": "#F3CD4A"},
    {"name": "Goldfinch", "code": "SW 6905", "hex": "#F5D65B"},
    {"name": "Eye Catching", "code": "SW 6914", "hex": "#F2C448"},
]

# ============================================
# FARROW & BALL - COMPREHENSIVE PALETTE
# ============================================
FARROW_BALL_COLORS = [
    # WHITES & NEUTRALS
    {"name": "All White", "code": "No.2005", "hex": "#FEFEFD"},
    {"name": "Pointing", "code": "No.2003", "hex": "#F9F4E8"},
    {"name": "White Tie", "code": "No.2002", "hex": "#F5F0E1"},
    {"name": "Wimborne White", "code": "No.239", "hex": "#F3EFE1"},
    {"name": "Slipper Satin", "code": "No.2004", "hex": "#EDE8DA"},
    {"name": "James White", "code": "No.2010", "hex": "#F4F1E6"},
    {"name": "Wevet", "code": "No.273", "hex": "#EDE9DF"},
    {"name": "Blackened", "code": "No.2011", "hex": "#E4E2D8"},
    {"name": "Strong White", "code": "No.2001", "hex": "#E8E5DD"},
    {"name": "Ammonite", "code": "No.274", "hex": "#DCD8CE"},
    {"name": "Cornforth White", "code": "No.228", "hex": "#D4D0C8"},
    {"name": "Skimming Stone", "code": "No.241", "hex": "#E0D8C8"},
    {"name": "Clunch", "code": "No.2009", "hex": "#E3D9C8"},
    {"name": "Lime White", "code": "No.1", "hex": "#E9E4D8"},
    {"name": "Dimity", "code": "No.2008", "hex": "#EBE1D1"},
    {"name": "String", "code": "No.8", "hex": "#D9CEB4"},
    {"name": "Matchstick", "code": "No.2013", "hex": "#E5D9C1"},
    {"name": "Tallow", "code": "No.203", "hex": "#E9E1CD"},
    {"name": "House White", "code": "No.2012", "hex": "#E7DBC5"},
    {"name": "Old White", "code": "No.4", "hex": "#DAD3C1"},
    {"name": "Off-White", "code": "No.3", "hex": "#E1D9C7"},
    # GRAYS
    {"name": "Elephant's Breath", "code": "No.229", "hex": "#C9C0B5"},
    {"name": "Pavilion Gray", "code": "No.242", "hex": "#B7B4A8"},
    {"name": "Manor House Gray", "code": "No.265", "hex": "#A5A093"},
    {"name": "Lamp Room Gray", "code": "No.88", "hex": "#8A887D"},
    {"name": "Mole's Breath", "code": "No.276", "hex": "#918B7D"},
    {"name": "Charleston Gray", "code": "No.243", "hex": "#908E85"},
    {"name": "Worsted", "code": "No.284", "hex": "#A5A296"},
    {"name": "Hardwick White", "code": "No.5", "hex": "#C6C2B5"},
    {"name": "Dimpse", "code": "No.277", "hex": "#BDB9AF"},
    {"name": "Purbeck Stone", "code": "No.275", "hex": "#B5AEA4"},
    {"name": "Mouse's Back", "code": "No.40", "hex": "#988C7B"},
    {"name": "London Clay", "code": "No.244", "hex": "#9A8B79"},
    {"name": "Dead Salmon", "code": "No.28", "hex": "#A8968A"},
    {"name": "Light Gray", "code": "No.17", "hex": "#C2BDB2"},
    {"name": "Shaded White", "code": "No.201", "hex": "#E5DED1"},
    {"name": "Shadow White", "code": "No.282", "hex": "#E5DFD4"},
    {"name": "Cromarty", "code": "No.285", "hex": "#C9C9C1"},
    {"name": "Peignoir", "code": "No.286", "hex": "#CFC8C1"},
    {"name": "Plummett", "code": "No.272", "hex": "#8E8C86"},
    {"name": "Downpipe", "code": "No.26", "hex": "#5B5D5E"},
    {"name": "Railings", "code": "No.31", "hex": "#3B3B3B"},
    {"name": "Off-Black", "code": "No.57", "hex": "#353535"},
    {"name": "Pitch Black", "code": "No.256", "hex": "#2A2A2A"},
    {"name": "Paean Black", "code": "No.294", "hex": "#3C3533"},
    {"name": "Tanner's Brown", "code": "No.255", "hex": "#443C36"},
    # BLUES
    {"name": "Hague Blue", "code": "No.30", "hex": "#3E5265"},
    {"name": "Stiffkey Blue", "code": "No.281", "hex": "#3E4C5C"},
    {"name": "Inchyra Blue", "code": "No.289", "hex": "#4C5355"},
    {"name": "De Nimes", "code": "No.299", "hex": "#697B87"},
    {"name": "Oval Room Blue", "code": "No.85", "hex": "#8DA4AA"},
    {"name": "Light Blue", "code": "No.22", "hex": "#9CB4BC"},
    {"name": "Lulworth Blue", "code": "No.89", "hex": "#9EBCCC"},
    {"name": "Parma Gray", "code": "No.27", "hex": "#9AAAB4"},
    {"name": "Skylight", "code": "No.205", "hex": "#C8D8DC"},
    {"name": "Borrowed Light", "code": "No.235", "hex": "#D6DFE0"},
    {"name": "Cabbage White", "code": "No.269", "hex": "#D7DFD8"},
    {"name": "Pale Powder", "code": "No.204", "hex": "#D6DCDC"},
    {"name": "Stone Blue", "code": "No.86", "hex": "#7A9CA8"},
    {"name": "Chinese Blue", "code": "No.90", "hex": "#6D8B9A"},
    {"name": "Cook's Blue", "code": "No.237", "hex": "#5C7A8A"},
    {"name": "Pitch Blue", "code": "No.220", "hex": "#3E5568"},
    {"name": "Drawing Room Blue", "code": "No.253", "hex": "#3B5568"},
    {"name": "Blue Gray", "code": "No.91", "hex": "#7D8E95"},
    # GREENS
    {"name": "Teresa's Green", "code": "No.236", "hex": "#A5B4A5"},
    {"name": "Vert de Terre", "code": "No.234", "hex": "#C3C7B8"},
    {"name": "Cooking Apple Green", "code": "No.32", "hex": "#BCC4A7"},
    {"name": "Card Room Green", "code": "No.79", "hex": "#6D7158"},
    {"name": "Studio Green", "code": "No.93", "hex": "#525C4F"},
    {"name": "Green Smoke", "code": "No.47", "hex": "#738B78"},
    {"name": "Calke Green", "code": "No.34", "hex": "#6B8070"},
    {"name": "Ball Green", "code": "No.75", "hex": "#7F9A7A"},
    {"name": "Breakfast Room Green", "code": "No.81", "hex": "#98A98A"},
    {"name": "Saxon Green", "code": "No.80", "hex": "#8A9E78"},
    {"name": "Yeabridge Green", "code": "No.287", "hex": "#7A8968"},
    {"name": "Bancha", "code": "No.298", "hex": "#515944"},
    {"name": "Duck Green", "code": "No.124", "hex": "#323D35"},
    {"name": "Beverly", "code": "No.310", "hex": "#577865"},
    {"name": "Treron", "code": "No.292", "hex": "#738A6A"},
    {"name": "Chappell Green", "code": "No.83", "hex": "#5C6B54"},
    {"name": "Mizzle", "code": "No.266", "hex": "#A8AE9C"},
    {"name": "French Gray", "code": "No.18", "hex": "#A9AFA5"},
    {"name": "Pigeon", "code": "No.25", "hex": "#9BA598"},
    {"name": "Blue Gray", "code": "No.91", "hex": "#7D8E95"},
    {"name": "Green Blue", "code": "No.84", "hex": "#8DAAA4"},
    {"name": "Dix Blue", "code": "No.82", "hex": "#7DA09C"},
    # REDS/PINKS
    {"name": "Rectory Red", "code": "No.217", "hex": "#8B4049"},
    {"name": "Incarnadine", "code": "No.248", "hex": "#954048"},
    {"name": "Eating Room Red", "code": "No.43", "hex": "#A43D42"},
    {"name": "Blazer", "code": "No.212", "hex": "#B53C40"},
    {"name": "Lake Red", "code": "No.269", "hex": "#9A4848"},
    {"name": "Radicchio", "code": "No.96", "hex": "#954A5B"},
    {"name": "Preference Red", "code": "No.297", "hex": "#90454A"},
    {"name": "Porphyry Pink", "code": "No.49", "hex": "#A08888"},
    {"name": "Sulking Room Pink", "code": "No.295", "hex": "#A08A88"},
    {"name": "Cinder Rose", "code": "No.246", "hex": "#C0A8A5"},
    {"name": "Pink Ground", "code": "No.202", "hex": "#E4D5CC"},
    {"name": "Setting Plaster", "code": "No.231", "hex": "#D8C8C0"},
    {"name": "Middleton Pink", "code": "No.245", "hex": "#E4D0C5"},
    {"name": "Calamine", "code": "No.230", "hex": "#E0D0CB"},
    {"name": "Nancy's Blushes", "code": "No.278", "hex": "#E8DCD5"},
    # YELLOWS/GOLDS
    {"name": "Farrow's Cream", "code": "No.67", "hex": "#E9D9B5"},
    {"name": "Cord", "code": "No.16", "hex": "#D8C89C"},
    {"name": "Hay", "code": "No.37", "hex": "#D1BB88"},
    {"name": "Print Room Yellow", "code": "No.69", "hex": "#D8B86A"},
    {"name": "India Yellow", "code": "No.66", "hex": "#D9A84C"},
    {"name": "Sudbury Yellow", "code": "No.51", "hex": "#D8C078"},
    {"name": "Dayroom Yellow", "code": "No.233", "hex": "#E8D898"},
    {"name": "Citron", "code": "No.74", "hex": "#D9CC88"},
    {"name": "Yellow Ground", "code": "No.218", "hex": "#E8D890"},
    {"name": "Babouche", "code": "No.223", "hex": "#E8C048"},
    {"name": "Hound Lemon", "code": "No.2", "hex": "#F0E098"},
]

# ============================================
# BEHR - COMPREHENSIVE PALETTE
# ============================================
BEHR_COLORS = [
    # WHITES
    {"name": "Ultra Pure White", "code": "PPU18-06", "hex": "#FFFFFF"},
    {"name": "Polar Bear", "code": "PPU18-07", "hex": "#F2F2ED"},
    {"name": "Cameo White", "code": "PPU7-11", "hex": "#EBE6DA"},
    {"name": "Swiss Coffee", "code": "PPU5-12", "hex": "#EDE4D4"},
    {"name": "Cottage White", "code": "PPU7-12", "hex": "#EDE5D5"},
    {"name": "Frost", "code": "PPU18-09", "hex": "#F0F0EB"},
    {"name": "Natural White", "code": "PPU18-11", "hex": "#EAE8E3"},
    {"name": "White Moderne", "code": "PPU18-08", "hex": "#EDECE8"},
    {"name": "Seagull White", "code": "ECC-30-1", "hex": "#F0EFEA"},
    {"name": "Nano White", "code": "PPU18-10", "hex": "#E9E7E2"},
    {"name": "Blank Canvas", "code": "DC-003", "hex": "#EDE8DC"},
    {"name": "White Clay", "code": "PPU18-16", "hex": "#E3E0DA"},
    {"name": "Painter's White", "code": "PPU18-14", "hex": "#E8E6E2"},
    {"name": "China Cup", "code": "S-G-10", "hex": "#ECE9E4"},
    {"name": "Silky White", "code": "PPU7-14", "hex": "#E8E5DD"},
    {"name": "Creamy Mushroom", "code": "PPU5-13", "hex": "#E1D8C8"},
    {"name": "Wheat Bread", "code": "PPU4-13", "hex": "#D8CDBB"},
    {"name": "Antique White", "code": "PPU5-11", "hex": "#E9E0CF"},
    {"name": "Linen White", "code": "PPU5-09", "hex": "#EEEADA"},
    {"name": "Off White", "code": "PPU5-10", "hex": "#EDE6DA"},
    # GRAYS
    {"name": "Gray Owl", "code": "PPU26-09", "hex": "#B8B5AB"},
    {"name": "Silver Drop", "code": "PPU26-11", "hex": "#C5C3BB"},
    {"name": "Classic Silver", "code": "PPU26-10", "hex": "#BDB9B1"},
    {"name": "Perfect Taupe", "code": "PPU18-13", "hex": "#9E978B"},
    {"name": "Intellectual", "code": "PPU18-14", "hex": "#6B655C"},
    {"name": "Dark Pewter", "code": "PPU18-04", "hex": "#494541"},
    {"name": "Black Suede", "code": "PPU18-20", "hex": "#3A3835"},
    {"name": "Limousine Leather", "code": "PPU18-19", "hex": "#2E2C2A"},
    {"name": "Elephant Skin", "code": "PPU18-16", "hex": "#8A847C"},
    {"name": "Pewter Mug", "code": "PPU18-17", "hex": "#7B7770"},
    {"name": "Stone Creek", "code": "PPU18-15", "hex": "#8F8980"},
    {"name": "Fashion Gray", "code": "PPU18-15", "hex": "#8F8980"},
    {"name": "Porpoise", "code": "PPU18-02", "hex": "#696460"},
    {"name": "Cracked Pepper", "code": "PPU18-01", "hex": "#585450"},
    {"name": "Dark Granite", "code": "PPU18-03", "hex": "#5A5652"},
    {"name": "Barnwood Gray", "code": "PPU24-19", "hex": "#9B9489"},
    {"name": "Creek Bend", "code": "PPU24-18", "hex": "#A39C91"},
    {"name": "Ashwood", "code": "PPU24-17", "hex": "#B0A99D"},
    {"name": "Gray Mist", "code": "PPU24-16", "hex": "#C0BAB0"},
    {"name": "Sculptor Clay", "code": "PPU24-15", "hex": "#CAC5BB"},
    # BLUES
    {"name": "Blueprint", "code": "S470-5", "hex": "#425E73"},
    {"name": "Dark Navy", "code": "PPU15-19", "hex": "#37414D"},
    {"name": "In The Navy", "code": "N510-7", "hex": "#2D3B4D"},
    {"name": "Nocturne Blue", "code": "HDC-CL-28", "hex": "#354555"},
    {"name": "Salty Sea", "code": "M510-6", "hex": "#485F71"},
    {"name": "Atlantis", "code": "PPU15-18", "hex": "#455768"},
    {"name": "Jean Jacket Blue", "code": "PPU15-17", "hex": "#5A6D7E"},
    {"name": "Blue Denim", "code": "PPU15-16", "hex": "#6C7E8E"},
    {"name": "Aged Denim", "code": "PPU15-15", "hex": "#7D8E9B"},
    {"name": "Breezy Blue", "code": "PPU15-14", "hex": "#8FA0AB"},
    {"name": "Light Drizzle", "code": "PPU15-13", "hex": "#A2B1B9"},
    {"name": "Misty Coast", "code": "PPU15-12", "hex": "#B4C1C7"},
    {"name": "Washed Denim", "code": "PPU15-11", "hex": "#C3CED2"},
    {"name": "Coastal Fog", "code": "PPU15-10", "hex": "#D4DBDE"},
    {"name": "Water", "code": "PPU13-20", "hex": "#90B4C3"},
    {"name": "Tranquil Sea", "code": "PPU13-11", "hex": "#9EBCC6"},
    {"name": "Light Drizzle", "code": "PPU13-14", "hex": "#9EBCC6"},
    {"name": "Watery", "code": "HDC-CT-26", "hex": "#B5D1D7"},
    {"name": "Soft Cloud", "code": "PPU13-15", "hex": "#CBDEE1"},
    {"name": "Fountain Spout", "code": "PPU13-16", "hex": "#D8E8EA"},
    # GREENS
    {"name": "Juniper Ash", "code": "PPU12-16", "hex": "#6B7B72"},
    {"name": "Dark Everglade", "code": "PPU11-19", "hex": "#4A5A52"},
    {"name": "Laurel Tree", "code": "PPU11-18", "hex": "#5A6B63"},
    {"name": "Mountain Olive", "code": "PPU11-17", "hex": "#6A7C73"},
    {"name": "Garden Topiary", "code": "PPU11-16", "hex": "#7A8C83"},
    {"name": "Thyme", "code": "PPU11-15", "hex": "#8B9C92"},
    {"name": "Frosted Sage", "code": "PPU11-14", "hex": "#9CADA2"},
    {"name": "Soft Sage", "code": "PPU11-13", "hex": "#ADBDB1"},
    {"name": "Muted Mint", "code": "PPU11-12", "hex": "#BFCEC2"},
    {"name": "Iced Marble", "code": "PPU11-11", "hex": "#D0DED3"},
    {"name": "Fresh Dew", "code": "PPU11-10", "hex": "#E0EDE3"},
    {"name": "Rye Grass", "code": "PPU10-20", "hex": "#708E70"},
    {"name": "Vine Leaf", "code": "PPU10-19", "hex": "#5D7A5B"},
    {"name": "Nature Green", "code": "PPU10-18", "hex": "#6D8B68"},
    {"name": "Gallery Green", "code": "PPU10-17", "hex": "#7D9B79"},
    {"name": "Garden Swing", "code": "PPU10-16", "hex": "#8DAA89"},
    {"name": "Crisp Celery", "code": "PPU10-15", "hex": "#9FBA99"},
    {"name": "Bok Choy", "code": "PPU10-14", "hex": "#B0C9AA"},
    {"name": "Mossy Bank", "code": "PPU10-13", "hex": "#C1D7BB"},
    {"name": "Healing Aloe", "code": "PPU10-12", "hex": "#D2E4CC"},
    # NEUTRALS/BEIGES
    {"name": "Toasted Almond", "code": "N200-3", "hex": "#C6B49E"},
    {"name": "Creamy Mushroom", "code": "PPU5-13", "hex": "#E1D8C8"},
    {"name": "Sand Dollar", "code": "N290-2", "hex": "#DED4C4"},
    {"name": "Sandstone", "code": "N270-3", "hex": "#C9B9A4"},
    {"name": "Dusty Olive", "code": "N320-3", "hex": "#BFAF95"},
    {"name": "Sahara Desert", "code": "N310-5", "hex": "#A89272"},
    {"name": "Caramel Latte", "code": "N270-5", "hex": "#A28E70"},
    {"name": "Butterscotch", "code": "N270-4", "hex": "#B9A281"},
    {"name": "Warm Nutmeg", "code": "N200-4", "hex": "#B9A48C"},
    {"name": "Safari", "code": "N220-4", "hex": "#B5A089"},
    {"name": "Ground Cumin", "code": "N240-4", "hex": "#B09980"},
    {"name": "Dusty Olive", "code": "N320-4", "hex": "#A89A7E"},
    {"name": "Gravel Path", "code": "N200-5", "hex": "#A89276"},
    {"name": "Cappuccino", "code": "N210-5", "hex": "#9E8570"},
    {"name": "Wood Bark", "code": "N180-6", "hex": "#8B7463"},
    # REDS/PINKS
    {"name": "Red Pepper", "code": "M150-7", "hex": "#983830"},
    {"name": "Volcanic", "code": "M170-7", "hex": "#9C3A38"},
    {"name": "Pomegranate", "code": "S-H-150", "hex": "#9A3438"},
    {"name": "Cinnamon Cherry", "code": "S-H-160", "hex": "#8B3D3D"},
    {"name": "Vintage Wine", "code": "PPU1-13", "hex": "#884848"},
    {"name": "Cherry Cola", "code": "PPU1-12", "hex": "#985858"},
    {"name": "Pale Coral", "code": "M170-3", "hex": "#E4B4AA"},
    {"name": "Coral Rose", "code": "M170-4", "hex": "#D49888"},
    {"name": "Rose Hip", "code": "M150-3", "hex": "#D8A898"},
    {"name": "Canyon Rose", "code": "M160-4", "hex": "#C89888"},
    # YELLOWS/GOLDS
    {"name": "Saffron", "code": "PPU6-16", "hex": "#D4A85A"},
    {"name": "Pumpkin", "code": "PPU6-15", "hex": "#DAB060"},
    {"name": "Sunstroke", "code": "PPU6-14", "hex": "#E0B868"},
    {"name": "Corn Stalk", "code": "PPU6-13", "hex": "#E5C070"},
    {"name": "Lemon", "code": "PPU6-12", "hex": "#EBC878"},
    {"name": "Butter Cookie", "code": "PPU6-11", "hex": "#F0D080"},
    {"name": "Soft Yellow", "code": "PPU6-10", "hex": "#F5D888"},
    {"name": "Morning Sunshine", "code": "PPU6-09", "hex": "#FAE090"},
    {"name": "Cream Gold", "code": "PPU6-08", "hex": "#F5E098"},
    {"name": "Pale Yellow", "code": "PPU6-07", "hex": "#F8E8A8"},
]

async def seed_comprehensive_paints():
    """Seed ALL paint colors"""
    print("Seeding comprehensive paint colors...")
    
    all_paints = [
        ("Benjamin Moore", BENJAMIN_MOORE_COLORS),
        ("Sherwin Williams", SHERWIN_WILLIAMS_COLORS),
        ("Farrow & Ball", FARROW_BALL_COLORS),
        ("Behr", BEHR_COLORS),
    ]
    
    count = 0
    for manufacturer, colors in all_paints:
        for c in colors:
            existing = await db.master_materials.find_one({
                "name": c["name"],
                "manufacturer": manufacturer,
                "category": "paint"
            })
            if not existing:
                doc = {
                    "id": str(uuid.uuid4()),
                    "name": c["name"],
                    "category": "paint",
                    "manufacturer": manufacturer,
                    "vendor": manufacturer,
                    "sku": c.get("code", ""),
                    "color": c["name"],
                    "color_code": c.get("hex", ""),
                    "pattern": "",
                    "width": None,
                    "height": None,
                    "repeat": None,
                    "price_per_unit": None,
                    "unit": "gallon",
                    "lead_time": "",
                    "photo_url": "",
                    "photo_data": "",
                    "notes": f"{manufacturer} {c.get('code', '')}",
                    "tags": ["paint", manufacturer.lower(), c["name"].lower()],
                    "is_paint_color": True,
                    "hex_color": c.get("hex", ""),
                    "created_at": datetime.now(timezone.utc).isoformat(),
                    "updated_at": datetime.now(timezone.utc).isoformat(),
                    "used_in_projects": []
                }
                await db.master_materials.insert_one(doc)
                count += 1
    
    print(f"Seeded {count} paint colors")
    return count

async def main():
    print("=" * 60)
    print("SEEDING COMPREHENSIVE PAINT DATABASE")
    print("=" * 60)
    
    count = await seed_comprehensive_paints()
    
    # Count totals by manufacturer
    bm_count = await db.master_materials.count_documents({"manufacturer": "Benjamin Moore", "category": "paint"})
    sw_count = await db.master_materials.count_documents({"manufacturer": "Sherwin Williams", "category": "paint"})
    fb_count = await db.master_materials.count_documents({"manufacturer": "Farrow & Ball", "category": "paint"})
    behr_count = await db.master_materials.count_documents({"manufacturer": "Behr", "category": "paint"})
    total = await db.master_materials.count_documents({"category": "paint"})
    
    print("=" * 60)
    print(f"Benjamin Moore: {bm_count} colors")
    print(f"Sherwin Williams: {sw_count} colors")
    print(f"Farrow & Ball: {fb_count} colors")
    print(f"Behr: {behr_count} colors")
    print(f"TOTAL PAINT COLORS: {total}")
    print("=" * 60)

if __name__ == "__main__":
    asyncio.run(main())
