"""
Vendor-specific configuration for product scraping.
Login URLs and credentials from user's spreadsheet.
"""

VENDOR_CONFIGS = {
    "fourhands.com": {
        "name": "Four Hands",
        "login_url": "https://fourhands.com/login?returnurl=%2fhome",
        "login_type": "direct",
        "extra_wait_before_login": 5000,
        "username_selectors": ['input[type="text"]', 'input[name="username"]', 'input[name="email"]', 'input[type="email"]', '#username', '#email'],
        "password_selectors": ['input[type="password"]', '#password', 'input[name="password"]'],
        "submit_selectors": ['button[type="submit"]', 'input[type="submit"]', 'button:has-text("Sign In")', 'button:has-text("Login")'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price', '[class*="price"]'],
        "sku_selectors": ['.sku', '[class*="sku"]'],
        "image_selectors": ['meta[property="og:image"]', '.product-image img'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "uttermost.com": {
        "name": "Uttermost",
        "login_url": "https://uttermost.com/",
        "login_type": "direct",
        "extra_wait_before_login": 8000,
        "username_selectors": ['input[type="email"]', 'input[name="email"]', '#email'],
        "password_selectors": ['input[type="password"]', '#password', 'input[name="password"]'],
        "submit_selectors": ['button:has-text("SIGN IN")', 'button:has-text("Sign In")', 'button[type="submit"]'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price', '[class*="price"]'],
        "sku_selectors": ['.sku', '[class*="sku"]'],
        "image_selectors": ['meta[property="og:image"]', '.product-image img'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 10000,
        "wait_for_content": 8000,
    },
    
    "globalviews.com": {
        "name": "Global Views",
        "login_url": "https://www.globalviews.com/",
        "login_type": "direct",
        "extra_wait_before_login": 5000,
        "username_selectors": ['input[type="email"]', '#email', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]', '#pass', 'input[name="password"]'],
        "submit_selectors": ['button[type="submit"]', 'button:has-text("Sign In")'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 8000,
        "wait_for_content": 5000,
    },
    
    "rowefurniture.com": {
        "name": "Rowe Furniture",
        "login_url": "https://rowefurniture.com/login",
        "login_type": "direct",
        "extra_wait_before_login": 3000,
        "username_selectors": ['input[type="email"]', '#CustomerEmail', 'input[name="customer[email]"]'],
        "password_selectors": ['input[type="password"]', '#CustomerPassword'],
        "submit_selectors": ['button[type="submit"]', 'input[type="submit"]'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "reginaandrew.com": {
        "name": "Regina Andrew",
        "login_url": "https://www.reginaandrew.com/?logoff=T&whence=",
        "login_type": "direct",
        "extra_wait_before_login": 5000,
        "username_selectors": ['input[type="email"]', 'input[name="email"]', 'input[name="username"]'],
        "password_selectors": ['input[type="password"]', 'input[name="password"]'],
        "submit_selectors": ['button[type="submit"]', 'button:has-text("Sign In")', 'button:has-text("Login")'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "bernhardt.com": {
        "name": "Bernhardt",
        "login_url": "https://www.bernhardt.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")', 'button:has-text("Trade")'],
        "username_selectors": ['input[type="text"]', 'input[name="username"]', 'input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 8000,
        "wait_for_content": 5000,
    },
    
    "loloirugs.com": {
        "name": "Loloi Rugs",
        "login_url": "https://loloirugs.com/collections/rugs-collections",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")', 'button:has-text("Sign In")'],
        "username_selectors": ['input[type="email"]', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "visualcomfort.com": {
        "name": "Visual Comfort",
        "login_url": "https://www.visualcomfort.com/customer/account/login/",
        "login_type": "direct",
        "extra_wait_before_login": 5000,
        "username_selectors": ['#email', 'input[type="email"]', 'input[name="login[username]"]'],
        "password_selectors": ['#pass', 'input[type="password"]', 'input[name="login[password]"]'],
        "submit_selectors": ['#send2', 'button[type="submit"]'],
        "name_selectors": ['h1.page-title span', 'h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.product.attribute.sku .value'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.product.attribute.dimensions'],
        "wait_after_login": 8000,
        "wait_for_content": 5000,
    },
    
    "hvlgroup.com": {
        "name": "HVL Group",
        "login_url": "https://www.hvlgroup.com/Auth/Login?returnUrl=%2F",
        "login_type": "direct",
        "extra_wait_before_login": 3000,
        "username_selectors": ['#Email', 'input[name="Email"]', 'input[type="email"]'],
        "password_selectors": ['#Password', 'input[name="Password"]', 'input[type="password"]'],
        "submit_selectors": ['button[type="submit"]', 'input[type="submit"]'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "vandh.com": {
        "name": "V and H",
        "login_url": "https://vandh.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "flowdecor.com": {
        "name": "Flow Decor",
        "login_url": "https://www.flowdecor.com/sign-in/",
        "login_type": "direct",
        "extra_wait_before_login": 3000,
        "username_selectors": ['input[type="email"]', '#email', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]', '#password'],
        "submit_selectors": ['button[type="submit"]', 'input[type="submit"]'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "crestviewcollection.com": {
        "name": "Crestview Collection",
        "login_url": "https://www.crestviewcollection.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "bassettmirror.com": {
        "name": "Bassett Mirror",
        "login_url": "https://www.bassettmirror.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "eichholtz.com": {
        "name": "Eichholtz",
        "login_url": "https://www.eichholtz.com/en/customer/account/login/",
        "login_type": "direct",
        "extra_wait_before_login": 5000,
        "username_selectors": ['#email', 'input[type="email"]'],
        "password_selectors": ['#pass', 'input[type="password"]'],
        "submit_selectors": ['#send2', 'button[type="submit"]'],
        "name_selectors": ['h1.page-title span', 'h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.product.attribute.sku .value'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 8000,
        "wait_for_content": 5000,
    },
    
    "myohamerica.com": {
        "name": "MYO America",
        "login_url": "https://myohamerica.com/customer/account/login/",
        "login_type": "direct",
        "extra_wait_before_login": 5000,
        "username_selectors": ['#email', 'input[type="email"]'],
        "password_selectors": ['#pass', 'input[type="password"]'],
        "submit_selectors": ['#send2', 'button[type="submit"]'],
        "name_selectors": ['h1.page-title span', 'h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.product.attribute.sku .value'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 8000,
        "wait_for_content": 5000,
    },
    
    "safavieh.com": {
        "name": "Safavieh",
        "login_url": "https://safavieh.com/dealer-login?redirect_to=/",
        "login_type": "direct",
        "extra_wait_before_login": 3000,
        "username_selectors": ['#user_login', 'input[name="log"]', 'input[name="username"]'],
        "password_selectors": ['#user_pass', 'input[name="pwd"]', 'input[type="password"]'],
        "submit_selectors": ['#wp-submit', 'input[type="submit"]', 'button[type="submit"]'],
        "name_selectors": ['h1', '.product-title'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "surya.com": {
        "name": "Surya",
        "login_url": "https://www.surya.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")', 'a:has-text("Sign In")'],
        "username_selectors": ['input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "zeevlighting.com": {
        "name": "Zeev Lighting",
        "login_url": "https://zeevlighting.com/index.php",
        "login_type": "direct",
        "extra_wait_before_login": 3000,
        "username_selectors": ['input[type="email"]', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]', 'input[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "hubbardtonforge.com": {
        "name": "Hubbardton Forge",
        "login_url": "https://hubbardtonforge.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "hinkley.com": {
        "name": "Hinkley",
        "login_url": "https://www.hinkley.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "elegantlighting.com": {
        "name": "Elegant Lighting",
        "login_url": "https://www.elegantlighting.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
    
    "gabby.com": {
        "name": "Gabby Home",
        "login_url": "https://gabby.com/",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    },
}


def get_vendor_config(domain: str) -> dict:
    """Get vendor configuration for a domain."""
    clean_domain = domain.lower().replace('www.', '')
    
    if clean_domain in VENDOR_CONFIGS:
        return VENDOR_CONFIGS[clean_domain]
    
    for vendor_domain, config in VENDOR_CONFIGS.items():
        if vendor_domain in clean_domain or clean_domain in vendor_domain:
            return config
    
    # Default config
    return {
        "name": clean_domain.replace('.com', '').title(),
        "login_url": f"https://{clean_domain}",
        "login_type": "modal",
        "extra_wait_before_login": 5000,
        "trade_button_selectors": ['a:has-text("Trade")', 'a:has-text("Login")'],
        "username_selectors": ['input[type="email"]', 'input[name="email"]'],
        "password_selectors": ['input[type="password"]'],
        "submit_selectors": ['button[type="submit"]'],
        "name_selectors": ['h1'],
        "price_selectors": ['.price'],
        "sku_selectors": ['.sku'],
        "image_selectors": ['meta[property="og:image"]'],
        "dimensions_selectors": ['.dimensions'],
        "wait_after_login": 5000,
        "wait_for_content": 3000,
    }
